language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

cache: pip

env:
  - NEO4J_ADDRESS="http://localhost:7474" NEO4J_USERNAME="neo4j" NEO4J_PASSWORD="neo4j" NEO4J_URL="http://localhost:7474"

jdk:
  - openjdk11

before_install:
  - wget dist.neo4j.org/neo4j-community-3.5.0-unix.tar.gz
  - tar -xzf neo4j-community-3.5.0-unix.tar.gz
  - sudo neo4j-community-3.5.0/bin/neo4j start


install:
  - pip install -r requirements.txt

script:
  - python -m pytest
