language: python
sudo: required

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

cache: pip

services:
  - neo4j

env:
  - NEO4J_ADDRESS="localhost:7474" NEO4J_USERNAME="neo4j" NEO4J_PASSWORD="neo4j"

install:
  - pip install -r requirements.txt

script:
  - python -m pytest
